version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./flyway-app
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE"
      SPRING_DATASOURCE_USERNAME: "$MYSQLDB_USER"
      SPRING_DATASOURCE_PASSWORD: "$MYSQLDB_ROOT_PASSWORD"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"     
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: